# Generated by Django 3.1.2 on 2020-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20201018_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='vezes_por_semana',
            field=models.IntegerField(choices=[(2, 'Duas'), (3, 'Tres'), (7, 'Sete')]),
        ),
    ]
