# Generated by Django 3.1.2 on 2020-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
