
export const GET_MODALIDADES = 'GET_MODALIDADES';
export const ADD_MODALIDADE = 'ADD_MODALIDADE';
export const GET_TURMAS = 'GET_TURMA';
export const GET_PLANOS = 'GET_PLANOS';

export const GET_EXAMES = 'GET_EXAMES';
export const GET_MATRICULA_PLANOS = 'GET_MATRICULA_PLANOS';
export const GET_MATRICULA_TURMAS = 'GET_MATRICULA_TURMAS';


export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';