
export const GET_MODALIDADES = 'GET_MODALIDADES';
export const GET_MODALIDADE = 'GET_MODALIDADE';
export const ADD_MODALIDADE = 'ADD_MODALIDADE';
export const DELETE_MODALIDADE = 'DELETE_MODALIDADE';
export const EDIT_MODALIDADE = 'EDIT_MODALIDADE';