# Generated by Django 3.1.2 on 2020-10-19 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='CPF deve conter 11 digitos, apenas números', regex='^[0-9]{11}$')])),
                ('RG', models.CharField(max_length=10, unique=True)),
                ('data_de_nascimento', models.DateField()),
                ('num_cartao_credito', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_cartao_credito', message='Cartao de credito deve conter 16 digitos, apenas números', regex='^[0-9]{16}$')])),
                ('bandeira_cartao_credito', models.CharField(max_length=16)),
                ('nome_completo_cartao_credito', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('tipo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='SEG', max_length=3)),
                ('horario', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_horario', message='Horario no formato HH:MM, minutos multiplos de 5', regex='^[0-2][0-9]:[0-5][0|5]$')])),
                ('vagas', models.PositiveSmallIntegerField()),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.modalidade')),
            ],
            options={
                'unique_together': {('modalidade', 'horario', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezes_por_semana', models.IntegerField(choices=[(2, 'Duas'), (3, 'Tres'), (7, 'Sete')])),
                ('tipo', models.CharField(choices=[('MES', 'Mensal'), ('SEM', 'Semestral'), ('ANO', 'Anual')], default='MES', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.modalidade')),
            ],
            options={
                'unique_together': {('vezes_por_semana', 'valor', 'modalidade')},
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pressao_sistolica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pressao_diastolica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('percentual_gordura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percentual_massa_magra', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imc', models.DecimalField(decimal_places=1, max_digits=3)),
                ('habilitado', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.cliente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.turma')),
            ],
            options={
                'unique_together': {('turma', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.plano')),
            ],
            options={
                'unique_together': {('plano', 'cliente')},
            },
        ),
    ]
