# Generated by Django 3.1.2 on 2020-10-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='gym_app.cliente'),
        ),
        migrations.AlterField(
            model_name='matriculaplano',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='gym_app.cliente'),
        ),
        migrations.AlterField(
            model_name='matriculaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='gym_app.turma'),
        ),
    ]
