# Generated by Django 3.1.2 on 2020-10-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='descricao',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
